### ISSUE TITLE
Is this a jew simulator ?

### ISSUE THREAD

**Issue by shika-blyat** [Butanium/Genetic_algorithm_for_3D_TSP_python#1]
First of all, hi and thanks a lot for making this marvelous tool available for the rest of the world.
GAF3TP seems really perfect, although something is still bothering me with it: what is it ? 
That looks a lot like a Jew Simulator game, is that it ?

Thanks in advance for your answer.

**Comment by Butanium** [comment]
Hey I apologize but it's not. Our goal is to do a spaceship simulator in which you make spaceships breed to produce faster spaceships which breed to produce faster spaceships which breed to produce faster spaceships which breed to produce faster spaceships which breed to produce faster spaceships which breed to produce faster spaceships which breed to produce faster spaceships which breed to produce faster spaceships which breed to produce faster spaceships etc.
I hope this answer to your question, deer shika!
